reorg

diff --git a/devops/ICP/Jenkinsfile b/devops/ICP/Jenkinsfile
--- a/devops/ICP/Jenkinsfile
+++ b/devops/ICP/Jenkinsfile
@@ -17,7 +17,15 @@ podTemplate(label: 'mypod',
       sh """
       #!/bin/bash
       if [ -z "${params.release_name}" ]; then
-        echo "[ERROR]: A release name has not been declared. Please declare a release name in your Jenkins release_name pipeline variable"
+        echo "[ERROR]: A release name has not been declared. Please declare it in a Jenkins pipeline variable called release_name"
+        exit 1
+      fi
+      if [ -z "${params.docker_registry}" ]; then
+        echo "[ERROR]: A Docker registry has not been declared. Please declare it in a Jenkins pipeline variable called docker_registry"
+        exit 1
+      fi
+      if [ -z "${params.namespace}" ]; then
+        echo "[ERROR]: A namespace has not been declared. Please declare it in a Jenkins pipeline variable called namespace"
         exit 1
       fi
       """
@@ -35,21 +43,11 @@ podTemplate(label: 'mypod',
       sh """
       #!/bin/bash
 
-      source devops/ICP/values.properties
-
       # If values are not declared by the user for the following variables, default values will be chosen.
-      if [ -n "${params.docker_registry}" ]; then
-        DOCKER_REGISTRY=${params.docker_registry}
-      fi
-      if [ -n "${params.namespace}" ]; then
-        NAMESPACE=${params.namespace}
-      fi
+
       if [ -n "${params.artifactory_url}" ]; then
         ARTIFACTORY_URL=${params.artifactory_url}
       fi
-      echo \${DOCKER_REGISTRY}
-      echo \${NAMESPACE}
-      echo \${ARTIFACTORY_URL}
       exit 1
       """
     }
@@ -58,8 +56,8 @@ podTemplate(label: 'mypod',
       stage('Compile code') {
         sh """
         #!/bin/bash
-        if [ -n "${ARTIFACTORY_URL}" ]; then
-          sed -i -- 's/ARTIFACTORY_URL_PLACEHOLDER/${ARTIFACTORY_URL}/g' artifactory_settings.xml
+        if [ -n "${params.artifactory_url}" ]; then
+          sed -i -- 's/ARTIFACTORY_URL_PLACEHOLDER/${params.artifactory_url}/g' artifactory_settings.xml
           mv artifactory_settings.xml /root/.m2/settings.xml
         fi
         exit 1
@@ -73,7 +71,7 @@ podTemplate(label: 'mypod',
         sh """
         #!/bin/bash
 
-        docker build -t ${DOCKER_REGISTRY}/${NAMESPACE}/wfd-appetizer-spring:${env.BUILD_NUMBER} .
+        docker build -t ${params.docker_registry}/${params.namespace}/wfd-appetizer-spring:${env.BUILD_NUMBER} .
         """
 
       }
@@ -84,10 +82,10 @@ podTemplate(label: 'mypod',
           #!/bin/bash
 
           set +x
-          docker login -u=${USERNAME} -p=${PASSWORD} ${DOCKER_REGISTRY}
+          docker login -u=${USERNAME} -p=${PASSWORD} ${params.docker_registry}
           set -x
 
-          docker push ${DOCKER_REGISTRY}/${NAMESPACE}/wfd-appetizer-spring:${env.BUILD_NUMBER}
+          docker push ${params.docker_registry}/${params.namespace}/wfd-appetizer-spring:${env.BUILD_NUMBER}
           """
         }
       }
@@ -100,7 +98,7 @@ podTemplate(label: 'mypod',
           DEPLOYMENT=`kubectl get deployments | grep ${params.release_name} | grep wfd-appetizer | awk '{print \$1}'`
 
           # Update Deployment
-          kubectl set image deployment/\${DEPLOYMENT} wfd-appetizer=${DOCKER_REGISTRY}/${NAMESPACE}/wfd-appetizer-spring:${env.BUILD_NUMBER}
+          kubectl set image deployment/\${DEPLOYMENT} wfd-appetizer=${params.docker_registry}/${params.namespace}/wfd-appetizer-spring:${env.BUILD_NUMBER}
           kubectl rollout status deployment/\${DEPLOYMENT}
         """
       }
